# Generated by Django 5.1 on 2024-12-19 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='balance_sheet',
            fields=[
                ('balance_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tot_assets', models.FloatField(blank=True, null=True)),
                ('tot_cur_assets', models.FloatField(blank=True, null=True)),
                ('inventories', models.FloatField(blank=True, null=True)),
                ('fix_assets', models.FloatField(blank=True, null=True)),
                ('tot_liab', models.FloatField(blank=True, null=True)),
                ('tot_non_cur_liab', models.FloatField(blank=True, null=True)),
                ('tot_cur_liab', models.FloatField(blank=True, null=True)),
                ('eqy_belongto_parcomsh', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comp_name_eng', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_swcode_2021', models.CharField(blank=True, max_length=50, null=True)),
                ('founddate1', models.DateField(blank=True, null=True)),
                ('regcapital', models.FloatField(blank=True, null=True)),
                ('employee', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('securities_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('sec_englishname', models.CharField(max_length=255)),
                ('ipo_date', models.DateField()),
                ('exch_eng', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='esg_data',
            fields=[
                ('esg_reportid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('esg_rating_wind', models.CharField(blank=True, max_length=50, null=True)),
                ('esg_escore_wind', models.FloatField(blank=True, null=True)),
                ('esg_sscore_wind', models.FloatField(blank=True, null=True)),
                ('esg_gscore_wind', models.FloatField(blank=True, null=True)),
                ('esg_rating_ftserussell', models.CharField(blank=True, max_length=50, null=True)),
                ('esg_mgmtscore_wind2', models.FloatField(blank=True, null=True)),
                ('esg_eventscore_wind2', models.FloatField(blank=True, null=True)),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg', to='queryapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='financial_analysis',
            fields=[
                ('faid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('eps_basic', models.FloatField(blank=True, null=True)),
                ('roe_basic', models.FloatField(blank=True, null=True)),
                ('profittogr', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('quick', models.FloatField(blank=True, null=True)),
                ('fa_debttoeqy', models.FloatField(blank=True, null=True)),
                ('invturndays', models.FloatField(blank=True, null=True)),
                ('invturn', models.FloatField(blank=True, null=True)),
                ('turnover_ttm', models.FloatField(blank=True, null=True)),
                ('yoy_tr', models.FloatField(blank=True, null=True)),
                ('yoyprofit', models.FloatField(blank=True, null=True)),
                ('balance_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialanalysis', to='queryapp.balance_sheet')),
            ],
        ),
        migrations.CreateModel(
            name='income_statement',
            fields=[
                ('income_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tot_oper_rev', models.FloatField(blank=True, null=True)),
                ('tot_oper_cost', models.FloatField(blank=True, null=True)),
                ('opprofit', models.FloatField(blank=True, null=True)),
                ('tot_profit', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('net_profit_is', models.FloatField(blank=True, null=True)),
                ('tot_compreh_inc_parent_comp', models.FloatField(blank=True, null=True)),
                ('selling_dist_exp', models.FloatField(blank=True, null=True)),
                ('gerl_admin_exp', models.FloatField(blank=True, null=True)),
                ('rd_exp', models.FloatField(blank=True, null=True)),
                ('fin_exp_is', models.FloatField(blank=True, null=True)),
                ('balance_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomestatements', to='queryapp.balance_sheet')),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='securities_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='queryapp.securities'),
        ),
        migrations.AddField(
            model_name='balance_sheet',
            name='windcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancesheets', to='queryapp.securities'),
        ),
    ]
